name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt codecov

      - name: Rodar Flake8
        run: flake8

      - name: Test with pytest and coverage
        run:
           pytest libpythonpro --cov=libpythonpro

      - name: Codecov
        uses: codecov/codecov-action@v3.0.0

      - name: Relatório coverage
        env:
          CODECOV_TOKEN: ${{ 1a0f3e8b-4fb4-412b-bacd-5b5d2d245bb9 }}
            run: |
              codecov





