name: Python application

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -q pipenv codecov
          pipenv sync --dev

      - name: Rodar Flake8
        run: pipenv run flake8

      - name: Test with pytest and coverage
        run:
           pipenv run pytest --cov=curso-django

      - name: Codecov
        uses: codecov/codecov-action@v3.0.0
        with:
          file: .coverage
          token: aba4df71-9b6b-4277-b00c-48a1e570b22b





